### ISSUE TITLE
Error loading file when running mjpeg-stream.js

### ISSUE THREAD

**Issue by ryanjbaxter** [hybridgroup/node-bebop#10]
I am trying to run the mjpeg-stream.js example but I am getting the error 

`[Error: Error loading file]`

Any idea why this is happening?  I am using node v0.12.4.

**Comment by deadprogram** [comment]
Hi @ryanjbaxter pretty sure that version of node is not yet supported by this module? I cannot recall why at the moment. Can you please try an older version and see if you have same problem?

**Comment by ryanjbaxter** [comment]
@deadprogram what version should i be using?

**Comment by deadprogram** [comment]
I'd try 0.10.X

**Comment by ryanjbaxter** [comment]
I switched to 0.10.38 and still see the same error.  I am OSX 10.10.5, not sure if that makes a difference.

**Comment by ryanjbaxter** [comment]
Anyone have any other suggestions as to why this is not working?

**Comment by deadprogram** [comment]
Do you have `ffmpeg` installed on your machine? I just realized the docs are missing the info that this is a needed prereq. The installation info for this on OSX  if you are using Homebrew is:

```
brew install ffmpeg
```

**Comment by ryanjbaxter** [comment]
yes I have ffmpeg installed

**Comment by nelson-liu** [comment]
ping @ryanjbaxter @deadprogram did you ever find a solution to this error?

**Comment by ryanjbaxter** [comment]
@nelson-liu no I did not

**Comment by deadprogram** [comment]
Hi, @ryanjbaxter can you please retry this code with the new 0.5.0 node-bebop release? I am not able to reproduce myself with this version. I will leave this issue open to await some additional info.

**Comment by deadprogram** [comment]
Closing due to age of issue. Please reopen if needed.
