### ISSUE TITLE
Support For Getting GPS Coordinates

### ISSUE THREAD

**Issue by ryanjbaxter** [hybridgroup/node-bebop#11]
Is it possible to add support for getting the GPS coordinates of the drone?

**Comment by deadprogram** [comment]
The Bebop API shows `PilotingStatePositionChanged` with a `PositionChanged` packet: https://github.com/Parrot-Developers/libARCommands/blob/master/Xml/ARDrone3_commands.xml#L539

So it *should* be possible.

**Comment by ryanjbaxter** [comment]
Any pointers on how to implement that?  Maybe an example of an existing event that is already implemented in the node bebop library?

**Comment by deadprogram** [comment]
This is the `FlyingStateChanged` packet code that is currently implemented:

https://github.com/hybridgroup/node-bebop/blob/master/lib/bebop.js#L241

**Comment by deadprogram** [comment]
Hi, @ryanjbaxter you can now get the GPS info as part of the `PositionChanged` message. Check out https://github.com/hybridgroup/node-bebop/blob/master/examples/gps.js

**Comment by ryanjbaxter** [comment]
Nice thanks I will take a look at it this week!  Has this been published to NPM?

**Comment by deadprogram** [comment]
Yes, published yesterday.

**Comment by deadprogram** [comment]
Hi @ryanjbaxter we've just released v0.5.0 which has many improvements including more support for the GPS events. Please give it a try, and if needed reopen this issue. Thanks!
