### ISSUE TITLE
newbie question. how can i get videostream off the bebop

### ISSUE THREAD

**Issue by uaedronemaster** [hybridgroup/node-bebop#14]
Hello,

i wanted to know how can i get live video stream on an http local host?

and any references i can learn from? 

thanks

**Comment by johan-olsson** [comment]
I think you will find this issue helpful #9

**Comment by uaedronemaster** [comment]
Hello Johan,

I tried the code as you told me to but i am getting the following error.
may you please help me identify the source of the error.

[image: Inline image 1]

**Comment by johan-olsson** [comment]
@uaedronemaster Think your image failed to upload or something.

**Comment by uaedronemaster** [comment]
I havent installed emscripton thou, its not mandatory right! plus is there
an issue with the code ?

**Comment by johan-olsson** [comment]
No it shouldn't be. But I meant that I can't see the image you posted of your error in your previous comment.

**Comment by uaedronemaster** [comment]
well do u see it now?

**Comment by uaedronemaster** [comment]
[image: Inline image 1]

**Comment by uaedronemaster** [comment]
![capture1](https://cloud.githubusercontent.com/assets/16239818/12066449/7e7e9926-b001-11e5-91a2-e643dadf6280.PNG)

**Comment by johan-olsson** [comment]
Does look like you haven't installed node-bebop. did you run `npm install node-bebop`?

**Comment by uaedronemaster** [comment]
yes it is installed globally

**Comment by uaedronemaster** [comment]
i installed it locally now it says 'Broadway-masterPlayerPlayer' module is
not found.... what is that

**Comment by johan-olsson** [comment]
Install it locally and try again. You shouldn't install it globally

**Comment by uaedronemaster** [comment]
Yes i did ... i got a new error now

**Comment by uaedronemaster** [comment]
![capture](https://cloud.githubusercontent.com/assets/16239818/12066910/951919c4-b009-11e5-8bb7-4bb8cd97b20e.PNG)

**Comment by uaedronemaster** [comment]
I posted the new error picture

**Comment by johan-olsson** [comment]
Maybe it's easier if you just post your code and I can have a look at it.

**Comment by uaedronemaster** [comment]
this is the code:

var bebop = require('node-bebop');
var Player = require('./Broadway-master/Player/Player');
var Drone = bebop.createClient();
var stream = Drone.getVideoStream();

var player = new Player({
    useWorker: true,
    workerFile: './NodejsConsoleApp3/Broadway-master/Player/Decoder.js'
});

document.body.appendChild(player.canvas);

var toUint8Array = function (parStr) {
    var raw = atob(parStr);
    var array = new Uint8Array(new ArrayBuffer(raw.length));

    Array.prototype.forEach.call(raw, function (data, index) {
        array[index] = raw.charCodeAt(index);
    })

    return array;
};

stream.on('data', function (data) {
    player.decode(toUint8Array(data.toString('base64')));
});

**Comment by johan-olsson** [comment]
Doesn't seem to be anything wrong with this assuming the paths are correct and you are creating an Electron app or similar. Is this the case?

**Comment by uaedronemaster** [comment]
no i am not making and electron app.. what is that and am i suppose to make
an electron app to get the video live steam?

**Comment by uaedronemaster** [comment]
I downloaded electron, but what should i do exactly? i am dragging and
dropping the visual studio .sln file in electron but it gives me an error?

**Comment by deadprogram** [comment]
@uaedronemaster I would not worry about Electron at this point, that was I think just a general question.

**Comment by uaedronemaster** [comment]
ah okay. but im not able to stream video yet ... help please

**Comment by johan-olsson** [comment]
Alright, in that case you have to divide the code to backend nodejs and client js with Broadway. Something like this should work assuming you are using browserify for the client.

Node part:
```JavaScript
var io = require('socket.io')(80);
var bebop = require('node-bebop');
var Drone = bebop.createClient();
var stream = Drone.getVideoStream();

var toUint8Array = function (parStr) {
    var raw = atob(parStr);
    var array = new Uint8Array(new ArrayBuffer(raw.length));

    Array.prototype.forEach.call(raw, function (data, index) {
        array[index] = raw.charCodeAt(index);
    })

    return array;
};

io.on('connection', function (socket) {
  socket.emit('user connected');
stream.on('data', function (data) {
    player.decode(toUint8Array(data.toString('base64')));
});

});
```

Client part:
```JavaScript

var Player = require('./Broadway-master/Player/Player');

  var socket = io('http://localhost/');
  socket.on('connect', function () {
    socket.send('hi');

    socket.on('message', function (msg) {
      // my msg
    });
  });
```

**Comment by johan-olsson** [comment]
@uaedronemaster I created a [project](https://github.com/johan-olsson/bebopBrowserVideo) for you to clone if you want an example on how to get it running.

**Comment by uaedronemaster** [comment]
Thanks!! but just one last question... i ran the app.js using node and it
works and connects to the drone.... but where can i watch my live video
feed? i dont know where to type gulp-watch ..... i downloaded the chrome
extension which is the gulp-devtools but is that related ?

**Comment by uaedronemaster** [comment]
Everything works well now including gulp watch... but the only problem is
that bufferutil module and utf8 cant be installed... it says error with
node-gyp rebuild ... cannot install optional dependencies. can you tell me
the version of nodejs and npm you are using ? thank you

**Comment by johan-olsson** [comment]
What bufferutil and utf8 can't be installed? Could you show me your installation error?

**Comment by uaedronemaster** [comment]
this is the error i get :

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.



[21:33:12] Using gulpfile ~\Desktop\Robotics\Parrot
Bebop\bebopBrowserVideo-master\gulpfile.js
[21:33:12] Starting 'html'...
[21:33:12] Starting 'broadway'...
[21:33:12] Starting 'fonts'...
[21:33:12] Finished 'fonts' after 77 μs
[21:33:12] Starting 'clean'...
[21:33:12] Finished 'clean' after 120 ms
[21:33:12] Starting 'moveCss'...
[21:33:12] Finished 'moveCss' after 1.84 ms
[21:33:12] Starting 'styles'...
[21:33:12] Finished 'styles' after 6.67 μs
[21:33:12] Starting 'scripts'...
[21:33:12] Starting 'bower'...
[21:33:12] Finished 'bower' after 4.62 μs
[21:33:12] all files 991 B
[21:33:12] Finished 'html' after 372 ms
[21:33:12] Finished 'broadway' after 189 ms
[BABEL] Note: The code generator has deoptimised the styling of
"C:/Users/Desktop/Robotics/Parrot
Bebop/bebopBrowserVideo-master/Broadway/Player/Decoder.js" as it exceeds
the max of "100KB".
[21:34:01] Browserify Error { [Error: Cannot find module 'utf-8-validate'
from 'C:\Users\Desktop\Robotics\Parrot
Bebop\bebopBrowserVideo-master\node_modules\ws\lib']
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
[21:34:01] Browserify Error { [Error: Cannot find module 'bufferutil' from
'C:\Users\Desktop\Robotics\Parrot
Bebop\bebopBrowserVideo-master\node_modules\ws\lib']
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }


On Mon, Jan 11, 2016 at 6:53 PM, Johan Olsson <notifications@github.com>
 wrote:

> What bufferutil and utf8 can't be installed? Could you show me your
> installation error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hybridgroup/node-bebop/issues/14#issuecomment-170577911>
> .
>
>

**Comment by johan-olsson** [comment]
I assume you have tried `npm install --save utf-8-validate bufferutil`? there might be some stuff that just don't come with node in windows. Never actually used it

**Comment by uaedronemaster** [comment]
what do you use? mac? linux?

**Comment by johan-olsson** [comment]
I use mac. But did you try to install the missing dependencies?

**Comment by uaedronemaster** [comment]
Yes I did , but it fails at node-gyp rebuild

**Comment by johan-olsson** [comment]
I really can't help you much with windows related issues. But the repository I linked you work so you should be able to google the more general errors you get

**Comment by leerlemoniii** [comment]
little late to this, but the node-gyp issues are likely because you are using a newer version of node.... I find that using nvm-windows on a windows box allows me to install and change node version (and npm) which then fixes most these node-gyp problems.  Newer (v4 and 5) nodes have issues with nodegyp stuff that was compiled with the old 0. vaersions... When node and IO merged.

**Comment by deadprogram** [comment]
Closing due to age of issue, and that the original point got a little lost. :) 

Please open new issues as needed, thanks everyone!
