### ISSUE TITLE
how can i get the height information?

### ISSUE THREAD

**Issue by xliefde** [hybridgroup/node-bebop#24]

**Comment by deadprogram** [comment]
Hi, @xliefde you should listen for the `AltitudeChanged` event: https://github.com/hybridgroup/node-bebop#altitudechanged

https://github.com/hybridgroup/node-bebop/blob/master/examples/events.js shows how to subscribe to events.

Hope that helps!

**Comment by xliefde** [comment]
it worked ! Thanks :)

**Comment by deadprogram** [comment]
Glad to hear it! 

Closing this issue.

**Comment by CE93Geek** [comment]
@xliefde hi, may I know how did it work with you? I subscribed the event and it was triggered even though bebop didn't takesoff yet, also it just indicated that the altitude changed, how can I get the exact height im meters for example?
