### ISSUE TITLE
Problem with battery get

### ISSUE THREAD

**Issue by brunoua** [hybridgroup/node-bebop#31]
Hi @deadprogram ,
I do not know if anyone has noticed, but the battery event is only released if the battery status change.

There is no possibility to pick immediately the battery status?

greetings

**Comment by deadprogram** [comment]
Hi @brunoua 

This is what starts the drone sending notifications for all state changes https://github.com/hybridgroup/node-bebop/blob/master/lib/bebop.js#L251 so I'm not sure there is anything to be done about that? You could perhaps try calling it again?

**Comment by brunoua** [comment]
Hi @deadprogram ,
It was my mistake. The problem is solved.

Thank you

**Comment by deadprogram** [comment]
OK, great. Closing.
