### ISSUE TITLE
Upgraded Firmware to 3.2.0 on BB Now can't connect

### ISSUE THREAD

**Issue by virtualcrosby** [hybridgroup/node-bebop#34]
I get a EHOSTUNREACH 192.168.1.102:44444 when i attempt to create the client now.

Are there any other steps needed to enable node-bebop with a v3.2.0 firmware on the BB?

**Comment by deadprogram** [comment]
Hi, @bcrosby333 I am running same firmware no such problem, and so are many others, so it not some inherent problem. 

I would suggest your verify that your computer is connected to the same WiFi as the drone provides, before running your node-bebop code.

Hope that helps!

**Comment by bcrosby333** [comment]
@deadprogram I am connecting to a AP via script after it starts up. See https://github.com/Parrot-Developers/Samples/wiki/Convert-Bebop-to-client-instead-of-access-point 

There is where it fails. So i am not sure if it has anything to do with the node-bebop code. B/c you are right that if i just connect to the Bebop directly it works fine. 

Any thoughts?

**Comment by deadprogram** [comment]
If you know the IP address of the Bebop, you can override in your code by using the `ip` option

```
var drone = bebop.createClient({ip: "YOUR REAL IPADDRESS GOES HERE"});
```

**Comment by bcrosby333** [comment]
Yep, that is how i connect. However it doesn't work when you modify the settings on the Bebop to connect to Wifi Access Point via it being the Access Point and you connecting to it.

**Comment by deadprogram** [comment]
It might be obvious, but you need to enter your bebop's IP address, not your computer's IP address.

How are you determining your bebop's IP address, by looking at your router?

One other thing to check, make sure your router is not setup to disallow connects between machines on the internal subnet, the way many hotel/conference wifi is setup..

Can I please see a sample of your code?

**Comment by deadprogram** [comment]
Since this appears to be something with the user's WiFi config and not node-bebop itself, I am closing. Thanks!
