### ISSUE TITLE
Movements

### ISSUE THREAD

**Issue by jackcwebb** [hybridgroup/node-bebop#4]
I am using this for a competition and I have a question for you. Is there any way of making the bebop move forwards or backwards using this library or is there any way you could update to add that functionality. It would be greatly appreciated.

**Comment by zankich** [comment]
@jackcwebb yes you can use the [forward](https://github.com/hybridgroup/node-bebop#forwardval) and [backward](https://github.com/hybridgroup/node-bebop#backwardval) functions to do that.
