### ISSUE TITLE
Drone movement not implemented?

### ISSUE THREAD

**Issue by phrohdoh** [hybridgroup/node-bebop#48]
Could someone clarify this please?

My understanding is that `moveBy{End}` are what actually make the Bebop 2 move (per the Parrot docs) so if these are not implemented that means I will be unable to move / flip / follow a flightplan with my drone, correct?

https://github.com/hybridgroup/node-bebop/blob/88512f1bfa0e8321c269961442a373fa4c9e1df5/docs/commands.md#pilotingmovebyobj

**Comment by deadprogram** [comment]
As of the last time I worked on this module, those commands were not yet implemented on Parrot's API. 

I suggest you use PCMD commands to move around, like the examples do, or else a flight plan created MAVLINK file.

Hope that helps!

Closing this issue, please reopen if needed.
