### ISSUE TITLE
keyboard control

### ISSUE THREAD

**Issue by Skorkmaz88** [hybridgroup/node-bebop#49]
Sorry it is not really a problem, I just wonder what would be the best approach to have control with the keyboard keys using this module. Currently, RTP example for firmware 4 seems to be working fine for video access, ideally it should be combined with video stream

**Comment by deadprogram** [comment]
I'd personally suggest using https://github.com/hybridgroup/cylon-bebop and https://github.com/hybridgroup/cylon-keyboard

Kind of like https://github.com/hybridgroup/cylon-bebop/blob/master/examples/bebop_dualshock3.js but replacing the joystick with the keyboard.

**Comment by Skorkmaz88** [comment]
yet, do they support, firmware 4 ?

**Comment by deadprogram** [comment]
cylon-bebop is a wrapper around node-bebop.

**Comment by Skorkmaz88** [comment]
cylon-bebop's new version causing a jump  before landing and acting weirdly, not able to land. It used work better. (currently ,Bebop 2, firmware 4.0), maybe I should add this issue to there.

**Comment by deadprogram** [comment]
Good idea, please do so. But I think it is using older node-bebop, likely, so probably that is the problem, it needs an update to the next node-bebop.

**Comment by Skorkmaz88** [comment]
Done so, I think this issue can be closed
