### ISSUE TITLE
Piloting

### ISSUE THREAD

**Issue by Mastuerso** [hybridgroup/node-bebop#64]
## I have this code:
```javascript

var bebop = require('node-bebop');
var drone = bebop.createClient();
var movement = new Object();
movement.dX = 0;
movement.dY = 0;
movement.dZ = 0;
movement.dPsi = 3.1416;

drone.connect(function () {
    drone.Piloting.takeOff();
    setTimeout(function() {
        drone.Piloting.moveBy(movement);
    }, 5000);
    setTimeout(function() {
        drone.Piloting.landing();
        console.log("LAND");
    }, 15000);
});
```
The drone takes off
Does nothing
Lands
I was wondering if there is a way to fix that because according to [http://developer.parrot.com/docs/reference/bebop/index.html#move-the-drone-to-a-relative-position](url) which is supportted since 3.3.0, currently my drone is running the 4.4.0

**Comment by muf** [comment]
@Mastuerso  
 `moveBy` function seems like not implemented yet.. only Draft :)
 link : https://github.com/hybridgroup/node-bebop/blob/master/docs/commands.md#pilotingmovebyobj
