### ISSUE TITLE
How to use events for Battery

### ISSUE THREAD

**Issue by dk683** [hybridgroup/node-bebop#7]
Hello! Thank you again for this nice code.
I am very new to node js. 
Could someone briefly give me an example how to use events? 
I am trying to display battery level, but I am having a difficulty.
Thank you!

**Comment by zankich** [comment]
@dk683 this example should do what you need
```javascript
"use strict";

var bebop = require("../.");
var drone = bebop.createClient();
drone.connect(function() {
  drone.on("battery", function(level) {
    console.log("battery level: " +  level);
  });
});
```

**Comment by dk683** [comment]
It perfectly works! Thank you for providing the code :+1:
